plugins:
  phan:
    enabled: true
    config:
      file_extensions: "php"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,design,naming,unusedcode"
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - tests/**
